set FN_AUTH_REDIRECT_URI=http://127.0.0.1:5000/google/auth
set FN_BASE_URI=# WRITE CODE TO REDIRECT TO YOUR PAGE
set FN_CLIENT_ID=# WRITE THE CLIENT ID AFTER YOU SET UP THE GOOGLE AUTH IN GOOGLE DEVELOPER
set FN_CLIENT_SECRET=rE9lFaPEtJnrwOmZfUOwNXSk

set FLASK_APP=app.py
set FLASK_DEBUG=1
set FN_FLASK_SECRET_KEY=SOMETHING RANDOM AND SECRET

python -m flask run -p 5000